### ISSUE TITLE
Research not working

### ISSUE THREAD

**Issue by Pragueham** [Theresmore-Automation/Theresmore-Automation#149]
[Game File](https://github.com/user-attachments/files/16050963/Theresmore_2024-07-01_10-41-14.txt)
[TheresmoreAutomationSettings.txt](https://github.com/user-attachments/files/16050977/TheresmoreAutomationSettings.txt)

For some reason research is no longer firing. Maybe something to do with the latest update? Have attached Game file and Settings file for your reference.

Have tried on multiple accounts on different computers. Running Chrome 125 on macOS (Sonoma).

**Comment by R4v3nl0** [comment]
I find that in `src/pages/research-research.js: 47`
`reactUtil.getNearestKey(button, 6)` will return `null`
so that it won't to click the research buttons : )

I am looking at how to solve the problem, wait a moment....

**Comment by R4v3nl0** [comment]
I had fix it.
See pr -> #150 
If you need to use it before merged, copy [this script](https://github.com/R4v3nl0/Theresmore-Automation/blob/main/dist/release-4.10.1.user.js) and overlay it into the original js script : )
Enjoy yourself!

**Comment by Pragueham** [comment]
Thank you!

**Comment by R4v3nl0** [comment]
> Thank you!

Hey, Pragueham! I add a shortcut (`ctrl + m`) for `maxResources`, if u need it, please use [this script](https://github.com/R4v3nl0/Theresmore-Automation/blob/main/dist/release-4.10.1.user.js). : )

If u wanna change the shortcut, clone the project, see the file `src/tasks/manageOptions.js`, line 1025 : )
And then run:
```shell
npm install
npm run build:release
```
Replace `dist/bundle.user.js` to your script : )
