### ISSUE TITLE
Feature suggestion: Hotkeys.

### ISSUE THREAD

**Issue by uNderdog101** [Theresmore-Automation/Theresmore-Automation#72]
It would be very convenient to have some hotkeys, or at the very least on for the "Max Resources" cheat, so you don't have to go into the menu every single time.

**Comment by R4v3nl0** [comment]
Hello uNderdog101, I add a shortcut for it, please view [this link](https://github.com/Theresmore-Automation/Theresmore-Automation/issues/149#issuecomment-2217785529)

**Comment by moriakaice** [comment]
I've merged in the PR with Ctrl + M for max resources
